"""
Constraint Engine — the realism gate for every generated transaction.

Design authority: dataset_config.py is the SINGLE source of channel/category/
limit truth (see docs/AUDIT.md rule 3). Nothing generated by red agents reaches
the blue team without passing every check here.

Checks (all deterministic, no LLM):
  C1 rail validity            — channel must exist in CHANNELS
  C2 category-rail pairing    — merchant_category valid for that channel
  C3 amount bounds            — within channel min/max AND category range
  C4 regulatory limits        — UPI/ATM/wallet single-txn caps
  C5 temporal plausibility    — IST timestamps, sane ordering, no future dates
  C6 device/location coherence— distance consistent with time delta between txns
"""
from __future__ import annotations

import sys
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any

_VENDOR_ML = Path(__file__).resolve().parents[3] / "vendor" / "argus" / "backend" / "ml"
if str(_VENDOR_ML) not in sys.path:
    sys.path.insert(0, str(_VENDOR_ML))

from dataset_config import (  # noqa: E402
    CATEGORY_AMOUNTS,
    CHANNELS,
    REGULATORY_LIMITS,
)


@dataclass
class Verdict:
    ok: bool
    failures: list[str] = field(default_factory=list)

    def __bool__(self) -> bool:
        return self.ok


def _fail(v: Verdict, code: str) -> None:
    v.failures.append(code)
    v.ok = False


def validate_txn(txn: dict[str, Any], *, prev_txn: dict[str, Any] | None = None) -> Verdict:
    v = Verdict(ok=True)
    try:
        amount = float(txn["amount"])
        channel = str(txn.get("channel", "")).lower()
    except (KeyError, TypeError, ValueError):
        _fail(v, "C0_missing_core_fields")
        return v

    # C1 rail validity
    cfg = CHANNELS.get(channel)
    if cfg is None:
        _fail(v, "C1_unknown_channel")
        return v

    # C2 category-rail pairing
    category = txn.get("merchant_category")
    if not isinstance(category, str) or category not in cfg["categories"]:
        _fail(v, "C2_invalid_category_for_channel")

    # C3 amount bounds (channel + category range)
    if amount < cfg["min"] or amount > cfg["max"]:
        _fail(v, "C3_amount_outside_channel_bounds")
    cat_range = CATEGORY_AMOUNTS.get(category or "")
    if cat_range and not (cat_range[0] <= amount <= cat_range[1]):
        _fail(v, "C3_amount_outside_category_range")

    # C4 regulatory caps
    if channel == "upi" and amount > REGULATORY_LIMITS["upi_single"]:
        _fail(v, "C4_upi_single_limit_exceeded")
    elif channel == "atm" and amount > REGULATORY_LIMITS["atm_single"]:
        _fail(v, "C4_atm_limit_exceeded")
    elif channel == "wallet" and amount > REGULATORY_LIMITS["wallet_single"]:
        _fail(v, "C4_wallet_limit_exceeded")

    # C5 temporal plausibility
    ts = txn.get("timestamp")
    if not isinstance(ts, datetime):
        _fail(v, "C5_timestamp_not_datetime")
    else:
        if ts.tzinfo is None:
            _fail(v, "C5_timestamp_naive_must_be_ist_aware")
        now = datetime.now(ts.tzinfo)
        if ts > now:
            _fail(v, "C5_timestamp_in_future")

    # C6 device/location coherence vs previous txn of same user
    dist = float(txn.get("location_distance_km", 0.0) or 0.0)
    if prev_txn is not None:
        pts = prev_txn.get("timestamp")
        if isinstance(pts, datetime) and isinstance(ts, datetime):
            hours = max((ts - pts).total_seconds() / 3600.0, 0.0)
            # physical limit ~900 km/h commercial flight
            if hours < 1e-6 and dist > 50:
                _fail(v, "C6_impossible_travel_zero_elapsed")
            elif hours > 0 and dist / max(hours, 1e-6) > 950.0:
                _fail(v, "C6_travel_faster_than_jet")

    return v


def validate_campaign(txns: list[dict[str, Any]], user_key: str = "user_id") -> dict[str, Any]:
    """Validate a full campaign stream; returns pass/fail stats + failure codes."""
    passed, failed, per_user_prev = 0, 0, {}
    failure_codes: dict[str, int] = {}
    for t in txns:
        key = t.get(user_key)
        verdict = validate_txn(t, prev_txn=per_user_prev.get(key))
        if verdict.ok:
            passed += 1
        else:
            failed += 1
            for code in verdict.failures:
                failure_codes[code] = failure_codes.get(code, 0) + 1
        if isinstance(t.get("timestamp"), datetime):
            per_user_prev[key] = t
    return {
        "total": len(txns), "passed": passed, "failed": failed,
        "pass_rate": round(passed / len(txns), 4) if txns else 0.0,
        "failure_codes": failure_codes,
    }


if __name__ == "__main__":
    from datetime import timedelta, timezone

    IST = timezone(timedelta(hours=5, minutes=30))
    good = {"amount": 450.0, "channel": "upi", "merchant_category": "Grocery",
            "timestamp": datetime(2026, 8, 24, 13, 0, tzinfo=IST), "user_id": "u1"}
    assert validate_txn(good).ok

    bad_cases = [
        {**good, "amount": 999_999.0},                       # C4 upi cap
        {**good, "channel": "atm"},                          # C2 ATM only Cash Withdrawal
        {**good, "amount": 250_000.0},                       # C3 category range
        {**good, "timestamp": "2026-08-24T13:00:00"},        # C5 string not datetime
    ]
    for b in bad_cases:
        res = validate_txn(b)
        assert not res.ok, f"expected failure: {b}"

    travel = {**good, "location_distance_km": 5000.0,
              "timestamp": datetime(2026, 8, 24, 13, 10, tzinfo=IST)}
    assert not validate_txn({**travel}, prev_txn={**good}).ok, "expected impossible-travel"

    print("[OK] constraint engine selftest: 6 checks exercised, all behave as specified")
